# Generated by Django 4.2 on 2023-04-07 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('año_de_fabricacion', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, max_length=240, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenautos')),
                ('fecha_de_edicion', models.DateField()),
                ('version', models.CharField(max_length=30)),
                ('motorizacion', models.CharField(max_length=30)),
                ('combustible', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
